site_name: yzyf1312.github.io
site_url: https://yzyf1312.github.io/
theme:
  name: material

markdown_extensions:
  # Python Markdown
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.highlight
  - pymdownx.superfences

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

  - pymdownx.tasklist:
      # custom_checkbox: true
      clickable_checkbox: true
  
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js